import Contacts
import Foundation

@_cdecl("cn_copy_contacts_constant")
public func cn_copy_contacts_constant(
  _ symbolName: UnsafePointer<CChar>?,
  _ outError: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?
) -> UnsafeMutablePointer<CChar>? {
  guard let symbolName else {
    cnrSetMessageError(outError, message: "missing Contacts constant symbol name")
    return nil
  }

  let symbol = String(cString: symbolName)
  switch symbol {
  case "CNContactPropertyNotFetchedExceptionName":
    return cnrCString(CNContactPropertyNotFetchedExceptionName)
  case "CNContactIdentifierKey":
    return cnrCString(CNContactIdentifierKey)
  case "CNContactNamePrefixKey":
    return cnrCString(CNContactNamePrefixKey)
  case "CNContactGivenNameKey":
    return cnrCString(CNContactGivenNameKey)
  case "CNContactMiddleNameKey":
    return cnrCString(CNContactMiddleNameKey)
  case "CNContactFamilyNameKey":
    return cnrCString(CNContactFamilyNameKey)
  case "CNContactPreviousFamilyNameKey":
    return cnrCString(CNContactPreviousFamilyNameKey)
  case "CNContactNameSuffixKey":
    return cnrCString(CNContactNameSuffixKey)
  case "CNContactNicknameKey":
    return cnrCString(CNContactNicknameKey)
  case "CNContactOrganizationNameKey":
    return cnrCString(CNContactOrganizationNameKey)
  case "CNContactDepartmentNameKey":
    return cnrCString(CNContactDepartmentNameKey)
  case "CNContactJobTitleKey":
    return cnrCString(CNContactJobTitleKey)
  case "CNContactPhoneticGivenNameKey":
    return cnrCString(CNContactPhoneticGivenNameKey)
  case "CNContactPhoneticMiddleNameKey":
    return cnrCString(CNContactPhoneticMiddleNameKey)
  case "CNContactPhoneticFamilyNameKey":
    return cnrCString(CNContactPhoneticFamilyNameKey)
  case "CNContactPhoneticOrganizationNameKey":
    return cnrCString(CNContactPhoneticOrganizationNameKey)
  case "CNContactBirthdayKey":
    return cnrCString(CNContactBirthdayKey)
  case "CNContactNonGregorianBirthdayKey":
    return cnrCString(CNContactNonGregorianBirthdayKey)
  case "CNContactNoteKey":
    return cnrCString(CNContactNoteKey)
  case "CNContactImageDataKey":
    return cnrCString(CNContactImageDataKey)
  case "CNContactThumbnailImageDataKey":
    return cnrCString(CNContactThumbnailImageDataKey)
  case "CNContactImageDataAvailableKey":
    return cnrCString(CNContactImageDataAvailableKey)
  case "CNContactTypeKey":
    return cnrCString(CNContactTypeKey)
  case "CNContactPhoneNumbersKey":
    return cnrCString(CNContactPhoneNumbersKey)
  case "CNContactEmailAddressesKey":
    return cnrCString(CNContactEmailAddressesKey)
  case "CNContactPostalAddressesKey":
    return cnrCString(CNContactPostalAddressesKey)
  case "CNContactDatesKey":
    return cnrCString(CNContactDatesKey)
  case "CNContactUrlAddressesKey":
    return cnrCString(CNContactUrlAddressesKey)
  case "CNContactRelationsKey":
    return cnrCString(CNContactRelationsKey)
  case "CNContactSocialProfilesKey":
    return cnrCString(CNContactSocialProfilesKey)
  case "CNContactInstantMessageAddressesKey":
    return cnrCString(CNContactInstantMessageAddressesKey)
  case "CNPostalAddressStreetKey":
    return cnrCString(CNPostalAddressStreetKey)
  case "CNPostalAddressSubLocalityKey":
    return cnrCString(CNPostalAddressSubLocalityKey)
  case "CNPostalAddressCityKey":
    return cnrCString(CNPostalAddressCityKey)
  case "CNPostalAddressSubAdministrativeAreaKey":
    return cnrCString(CNPostalAddressSubAdministrativeAreaKey)
  case "CNPostalAddressStateKey":
    return cnrCString(CNPostalAddressStateKey)
  case "CNPostalAddressPostalCodeKey":
    return cnrCString(CNPostalAddressPostalCodeKey)
  case "CNPostalAddressCountryKey":
    return cnrCString(CNPostalAddressCountryKey)
  case "CNPostalAddressISOCountryCodeKey":
    return cnrCString(CNPostalAddressISOCountryCodeKey)
  case "CNInstantMessageAddressUsernameKey":
    return cnrCString(CNInstantMessageAddressUsernameKey)
  case "CNInstantMessageAddressServiceKey":
    return cnrCString(CNInstantMessageAddressServiceKey)
  case "CNInstantMessageServiceAIM":
    return cnrCString(CNInstantMessageServiceAIM)
  case "CNInstantMessageServiceFacebook":
    return cnrCString(CNInstantMessageServiceFacebook)
  case "CNInstantMessageServiceGaduGadu":
    return cnrCString(CNInstantMessageServiceGaduGadu)
  case "CNInstantMessageServiceGoogleTalk":
    return cnrCString(CNInstantMessageServiceGoogleTalk)
  case "CNInstantMessageServiceICQ":
    return cnrCString(CNInstantMessageServiceICQ)
  case "CNInstantMessageServiceJabber":
    return cnrCString(CNInstantMessageServiceJabber)
  case "CNInstantMessageServiceMSN":
    return cnrCString(CNInstantMessageServiceMSN)
  case "CNInstantMessageServiceQQ":
    return cnrCString(CNInstantMessageServiceQQ)
  case "CNInstantMessageServiceSkype":
    return cnrCString(CNInstantMessageServiceSkype)
  case "CNInstantMessageServiceYahoo":
    return cnrCString(CNInstantMessageServiceYahoo)
  case "CNSocialProfileURLStringKey":
    return cnrCString(CNSocialProfileURLStringKey)
  case "CNSocialProfileUsernameKey":
    return cnrCString(CNSocialProfileUsernameKey)
  case "CNSocialProfileUserIdentifierKey":
    return cnrCString(CNSocialProfileUserIdentifierKey)
  case "CNSocialProfileServiceKey":
    return cnrCString(CNSocialProfileServiceKey)
  case "CNSocialProfileServiceFacebook":
    return cnrCString(CNSocialProfileServiceFacebook)
  case "CNSocialProfileServiceFlickr":
    return cnrCString(CNSocialProfileServiceFlickr)
  case "CNSocialProfileServiceLinkedIn":
    return cnrCString(CNSocialProfileServiceLinkedIn)
  case "CNSocialProfileServiceMySpace":
    return cnrCString(CNSocialProfileServiceMySpace)
  case "CNSocialProfileServiceSinaWeibo":
    return cnrCString(CNSocialProfileServiceSinaWeibo)
  case "CNSocialProfileServiceTencentWeibo":
    return cnrCString(CNSocialProfileServiceTencentWeibo)
  case "CNSocialProfileServiceTwitter":
    return cnrCString(CNSocialProfileServiceTwitter)
  case "CNSocialProfileServiceYelp":
    return cnrCString(CNSocialProfileServiceYelp)
  case "CNSocialProfileServiceGameCenter":
    return cnrCString(CNSocialProfileServiceGameCenter)
  case "CNContainerIdentifierKey":
    return cnrCString(CNContainerIdentifierKey)
  case "CNContainerNameKey":
    return cnrCString(CNContainerNameKey)
  case "CNContainerTypeKey":
    return cnrCString(CNContainerTypeKey)
  case "CNGroupIdentifierKey":
    return cnrCString(CNGroupIdentifierKey)
  case "CNGroupNameKey":
    return cnrCString(CNGroupNameKey)
  case "CNErrorDomain":
    return cnrCString(CNErrorDomain)
  case "CNErrorUserInfoAffectedRecordsKey":
    return cnrCString(CNErrorUserInfoAffectedRecordsKey)
  case "CNErrorUserInfoAffectedRecordIdentifiersKey":
    return cnrCString(CNErrorUserInfoAffectedRecordIdentifiersKey)
  case "CNErrorUserInfoValidationErrorsKey":
    return cnrCString(CNErrorUserInfoValidationErrorsKey)
  case "CNErrorUserInfoKeyPathsKey":
    return cnrCString(CNErrorUserInfoKeyPathsKey)
  case "CNLabelHome":
    return cnrCString(CNLabelHome)
  case "CNLabelWork":
    return cnrCString(CNLabelWork)
  case "CNLabelSchool":
    return cnrCString(CNLabelSchool)
  case "CNLabelOther":
    return cnrCString(CNLabelOther)
  case "CNLabelEmailiCloud":
    return cnrCString(CNLabelEmailiCloud)
  case "CNLabelURLAddressHomePage":
    return cnrCString(CNLabelURLAddressHomePage)
  case "CNLabelDateAnniversary":
    return cnrCString(CNLabelDateAnniversary)
  case "CNLabelPhoneNumberiPhone":
    return cnrCString(CNLabelPhoneNumberiPhone)
  case "CNLabelPhoneNumberAppleWatch":
    return cnrCString(CNLabelPhoneNumberAppleWatch)
  case "CNLabelPhoneNumberMobile":
    return cnrCString(CNLabelPhoneNumberMobile)
  case "CNLabelPhoneNumberMain":
    return cnrCString(CNLabelPhoneNumberMain)
  case "CNLabelPhoneNumberHomeFax":
    return cnrCString(CNLabelPhoneNumberHomeFax)
  case "CNLabelPhoneNumberWorkFax":
    return cnrCString(CNLabelPhoneNumberWorkFax)
  case "CNLabelPhoneNumberOtherFax":
    return cnrCString(CNLabelPhoneNumberOtherFax)
  case "CNLabelPhoneNumberPager":
    return cnrCString(CNLabelPhoneNumberPager)
  case "CNLabelContactRelationAssistant":
    return cnrCString(CNLabelContactRelationAssistant)
  case "CNLabelContactRelationManager":
    return cnrCString(CNLabelContactRelationManager)
  case "CNLabelContactRelationColleague":
    return cnrCString(CNLabelContactRelationColleague)
  case "CNLabelContactRelationTeacher":
    return cnrCString(CNLabelContactRelationTeacher)
  case "CNLabelContactRelationSibling":
    return cnrCString(CNLabelContactRelationSibling)
  case "CNLabelContactRelationYoungerSibling":
    return cnrCString(CNLabelContactRelationYoungerSibling)
  case "CNLabelContactRelationElderSibling":
    return cnrCString(CNLabelContactRelationElderSibling)
  case "CNLabelContactRelationSister":
    return cnrCString(CNLabelContactRelationSister)
  case "CNLabelContactRelationYoungerSister":
    return cnrCString(CNLabelContactRelationYoungerSister)
  case "CNLabelContactRelationYoungestSister":
    return cnrCString(CNLabelContactRelationYoungestSister)
  case "CNLabelContactRelationElderSister":
    return cnrCString(CNLabelContactRelationElderSister)
  case "CNLabelContactRelationEldestSister":
    return cnrCString(CNLabelContactRelationEldestSister)
  case "CNLabelContactRelationBrother":
    return cnrCString(CNLabelContactRelationBrother)
  case "CNLabelContactRelationYoungerBrother":
    return cnrCString(CNLabelContactRelationYoungerBrother)
  case "CNLabelContactRelationYoungestBrother":
    return cnrCString(CNLabelContactRelationYoungestBrother)
  case "CNLabelContactRelationElderBrother":
    return cnrCString(CNLabelContactRelationElderBrother)
  case "CNLabelContactRelationEldestBrother":
    return cnrCString(CNLabelContactRelationEldestBrother)
  case "CNLabelContactRelationFriend":
    return cnrCString(CNLabelContactRelationFriend)
  case "CNLabelContactRelationMaleFriend":
    return cnrCString(CNLabelContactRelationMaleFriend)
  case "CNLabelContactRelationFemaleFriend":
    return cnrCString(CNLabelContactRelationFemaleFriend)
  case "CNLabelContactRelationSpouse":
    return cnrCString(CNLabelContactRelationSpouse)
  case "CNLabelContactRelationWife":
    return cnrCString(CNLabelContactRelationWife)
  case "CNLabelContactRelationHusband":
    return cnrCString(CNLabelContactRelationHusband)
  case "CNLabelContactRelationPartner":
    return cnrCString(CNLabelContactRelationPartner)
  case "CNLabelContactRelationMalePartner":
    return cnrCString(CNLabelContactRelationMalePartner)
  case "CNLabelContactRelationFemalePartner":
    return cnrCString(CNLabelContactRelationFemalePartner)
  case "CNLabelContactRelationGirlfriendOrBoyfriend":
    return cnrCString(CNLabelContactRelationGirlfriendOrBoyfriend)
  case "CNLabelContactRelationGirlfriend":
    return cnrCString(CNLabelContactRelationGirlfriend)
  case "CNLabelContactRelationBoyfriend":
    return cnrCString(CNLabelContactRelationBoyfriend)
  case "CNLabelContactRelationParent":
    return cnrCString(CNLabelContactRelationParent)
  case "CNLabelContactRelationMother":
    return cnrCString(CNLabelContactRelationMother)
  case "CNLabelContactRelationFather":
    return cnrCString(CNLabelContactRelationFather)
  case "CNLabelContactRelationChild":
    return cnrCString(CNLabelContactRelationChild)
  case "CNLabelContactRelationDaughter":
    return cnrCString(CNLabelContactRelationDaughter)
  case "CNLabelContactRelationSon":
    return cnrCString(CNLabelContactRelationSon)
  case "CNLabelContactRelationGrandparent":
    return cnrCString(CNLabelContactRelationGrandparent)
  case "CNLabelContactRelationGrandmother":
    return cnrCString(CNLabelContactRelationGrandmother)
  case "CNLabelContactRelationGrandmotherMothersMother":
    return cnrCString(CNLabelContactRelationGrandmotherMothersMother)
  case "CNLabelContactRelationGrandmotherFathersMother":
    return cnrCString(CNLabelContactRelationGrandmotherFathersMother)
  case "CNLabelContactRelationGrandfather":
    return cnrCString(CNLabelContactRelationGrandfather)
  case "CNLabelContactRelationGrandfatherMothersFather":
    return cnrCString(CNLabelContactRelationGrandfatherMothersFather)
  case "CNLabelContactRelationGrandfatherFathersFather":
    return cnrCString(CNLabelContactRelationGrandfatherFathersFather)
  case "CNLabelContactRelationGreatGrandparent":
    return cnrCString(CNLabelContactRelationGreatGrandparent)
  case "CNLabelContactRelationGreatGrandmother":
    return cnrCString(CNLabelContactRelationGreatGrandmother)
  case "CNLabelContactRelationGreatGrandfather":
    return cnrCString(CNLabelContactRelationGreatGrandfather)
  case "CNLabelContactRelationGrandchild":
    return cnrCString(CNLabelContactRelationGrandchild)
  case "CNLabelContactRelationGranddaughter":
    return cnrCString(CNLabelContactRelationGranddaughter)
  case "CNLabelContactRelationGranddaughterDaughtersDaughter":
    return cnrCString(CNLabelContactRelationGranddaughterDaughtersDaughter)
  case "CNLabelContactRelationGranddaughterSonsDaughter":
    return cnrCString(CNLabelContactRelationGranddaughterSonsDaughter)
  case "CNLabelContactRelationGrandson":
    return cnrCString(CNLabelContactRelationGrandson)
  case "CNLabelContactRelationGrandsonDaughtersSon":
    return cnrCString(CNLabelContactRelationGrandsonDaughtersSon)
  case "CNLabelContactRelationGrandsonSonsSon":
    return cnrCString(CNLabelContactRelationGrandsonSonsSon)
  case "CNLabelContactRelationGreatGrandchild":
    return cnrCString(CNLabelContactRelationGreatGrandchild)
  case "CNLabelContactRelationGreatGranddaughter":
    return cnrCString(CNLabelContactRelationGreatGranddaughter)
  case "CNLabelContactRelationGreatGrandson":
    return cnrCString(CNLabelContactRelationGreatGrandson)
  case "CNLabelContactRelationParentInLaw":
    return cnrCString(CNLabelContactRelationParentInLaw)
  case "CNLabelContactRelationMotherInLaw":
    return cnrCString(CNLabelContactRelationMotherInLaw)
  case "CNLabelContactRelationMotherInLawWifesMother":
    return cnrCString(CNLabelContactRelationMotherInLawWifesMother)
  case "CNLabelContactRelationMotherInLawHusbandsMother":
    return cnrCString(CNLabelContactRelationMotherInLawHusbandsMother)
  case "CNLabelContactRelationFatherInLaw":
    return cnrCString(CNLabelContactRelationFatherInLaw)
  case "CNLabelContactRelationFatherInLawWifesFather":
    return cnrCString(CNLabelContactRelationFatherInLawWifesFather)
  case "CNLabelContactRelationFatherInLawHusbandsFather":
    return cnrCString(CNLabelContactRelationFatherInLawHusbandsFather)
  case "CNLabelContactRelationCoParentInLaw":
    return cnrCString(CNLabelContactRelationCoParentInLaw)
  case "CNLabelContactRelationCoMotherInLaw":
    return cnrCString(CNLabelContactRelationCoMotherInLaw)
  case "CNLabelContactRelationCoFatherInLaw":
    return cnrCString(CNLabelContactRelationCoFatherInLaw)
  case "CNLabelContactRelationSiblingInLaw":
    return cnrCString(CNLabelContactRelationSiblingInLaw)
  case "CNLabelContactRelationYoungerSiblingInLaw":
    return cnrCString(CNLabelContactRelationYoungerSiblingInLaw)
  case "CNLabelContactRelationElderSiblingInLaw":
    return cnrCString(CNLabelContactRelationElderSiblingInLaw)
  case "CNLabelContactRelationSisterInLaw":
    return cnrCString(CNLabelContactRelationSisterInLaw)
  case "CNLabelContactRelationYoungerSisterInLaw":
    return cnrCString(CNLabelContactRelationYoungerSisterInLaw)
  case "CNLabelContactRelationElderSisterInLaw":
    return cnrCString(CNLabelContactRelationElderSisterInLaw)
  case "CNLabelContactRelationSisterInLawSpousesSister":
    return cnrCString(CNLabelContactRelationSisterInLawSpousesSister)
  case "CNLabelContactRelationSisterInLawWifesSister":
    return cnrCString(CNLabelContactRelationSisterInLawWifesSister)
  case "CNLabelContactRelationSisterInLawHusbandsSister":
    return cnrCString(CNLabelContactRelationSisterInLawHusbandsSister)
  case "CNLabelContactRelationSisterInLawBrothersWife":
    return cnrCString(CNLabelContactRelationSisterInLawBrothersWife)
  case "CNLabelContactRelationSisterInLawYoungerBrothersWife":
    return cnrCString(CNLabelContactRelationSisterInLawYoungerBrothersWife)
  case "CNLabelContactRelationSisterInLawElderBrothersWife":
    return cnrCString(CNLabelContactRelationSisterInLawElderBrothersWife)
  case "CNLabelContactRelationBrotherInLaw":
    return cnrCString(CNLabelContactRelationBrotherInLaw)
  case "CNLabelContactRelationYoungerBrotherInLaw":
    return cnrCString(CNLabelContactRelationYoungerBrotherInLaw)
  case "CNLabelContactRelationElderBrotherInLaw":
    return cnrCString(CNLabelContactRelationElderBrotherInLaw)
  case "CNLabelContactRelationBrotherInLawSpousesBrother":
    return cnrCString(CNLabelContactRelationBrotherInLawSpousesBrother)
  case "CNLabelContactRelationBrotherInLawHusbandsBrother":
    return cnrCString(CNLabelContactRelationBrotherInLawHusbandsBrother)
  case "CNLabelContactRelationBrotherInLawWifesBrother":
    return cnrCString(CNLabelContactRelationBrotherInLawWifesBrother)
  case "CNLabelContactRelationBrotherInLawSistersHusband":
    return cnrCString(CNLabelContactRelationBrotherInLawSistersHusband)
  case "CNLabelContactRelationBrotherInLawYoungerSistersHusband":
    return cnrCString(CNLabelContactRelationBrotherInLawYoungerSistersHusband)
  case "CNLabelContactRelationBrotherInLawElderSistersHusband":
    return cnrCString(CNLabelContactRelationBrotherInLawElderSistersHusband)
  case "CNLabelContactRelationSisterInLawWifesBrothersWife":
    return cnrCString(CNLabelContactRelationSisterInLawWifesBrothersWife)
  case "CNLabelContactRelationSisterInLawHusbandsBrothersWife":
    return cnrCString(CNLabelContactRelationSisterInLawHusbandsBrothersWife)
  case "CNLabelContactRelationBrotherInLawWifesSistersHusband":
    return cnrCString(CNLabelContactRelationBrotherInLawWifesSistersHusband)
  case "CNLabelContactRelationBrotherInLawHusbandsSistersHusband":
    return cnrCString(CNLabelContactRelationBrotherInLawHusbandsSistersHusband)
  case "CNLabelContactRelationCoSiblingInLaw":
    return cnrCString(CNLabelContactRelationCoSiblingInLaw)
  case "CNLabelContactRelationCoSisterInLaw":
    return cnrCString(CNLabelContactRelationCoSisterInLaw)
  case "CNLabelContactRelationCoBrotherInLaw":
    return cnrCString(CNLabelContactRelationCoBrotherInLaw)
  case "CNLabelContactRelationChildInLaw":
    return cnrCString(CNLabelContactRelationChildInLaw)
  case "CNLabelContactRelationDaughterInLaw":
    return cnrCString(CNLabelContactRelationDaughterInLaw)
  case "CNLabelContactRelationSonInLaw":
    return cnrCString(CNLabelContactRelationSonInLaw)
  case "CNLabelContactRelationCousin":
    return cnrCString(CNLabelContactRelationCousin)
  case "CNLabelContactRelationYoungerCousin":
    return cnrCString(CNLabelContactRelationYoungerCousin)
  case "CNLabelContactRelationElderCousin":
    return cnrCString(CNLabelContactRelationElderCousin)
  case "CNLabelContactRelationMaleCousin":
    return cnrCString(CNLabelContactRelationMaleCousin)
  case "CNLabelContactRelationFemaleCousin":
    return cnrCString(CNLabelContactRelationFemaleCousin)
  case "CNLabelContactRelationCousinParentsSiblingsChild":
    return cnrCString(CNLabelContactRelationCousinParentsSiblingsChild)
  case "CNLabelContactRelationCousinParentsSiblingsSon":
    return cnrCString(CNLabelContactRelationCousinParentsSiblingsSon)
  case "CNLabelContactRelationYoungerCousinParentsSiblingsSon":
    return cnrCString(CNLabelContactRelationYoungerCousinParentsSiblingsSon)
  case "CNLabelContactRelationElderCousinParentsSiblingsSon":
    return cnrCString(CNLabelContactRelationElderCousinParentsSiblingsSon)
  case "CNLabelContactRelationCousinParentsSiblingsDaughter":
    return cnrCString(CNLabelContactRelationCousinParentsSiblingsDaughter)
  case "CNLabelContactRelationYoungerCousinParentsSiblingsDaughter":
    return cnrCString(CNLabelContactRelationYoungerCousinParentsSiblingsDaughter)
  case "CNLabelContactRelationElderCousinParentsSiblingsDaughter":
    return cnrCString(CNLabelContactRelationElderCousinParentsSiblingsDaughter)
  case "CNLabelContactRelationCousinMothersSistersDaughter":
    return cnrCString(CNLabelContactRelationCousinMothersSistersDaughter)
  case "CNLabelContactRelationYoungerCousinMothersSistersDaughter":
    return cnrCString(CNLabelContactRelationYoungerCousinMothersSistersDaughter)
  case "CNLabelContactRelationElderCousinMothersSistersDaughter":
    return cnrCString(CNLabelContactRelationElderCousinMothersSistersDaughter)
  case "CNLabelContactRelationCousinMothersSistersSon":
    return cnrCString(CNLabelContactRelationCousinMothersSistersSon)
  case "CNLabelContactRelationYoungerCousinMothersSistersSon":
    return cnrCString(CNLabelContactRelationYoungerCousinMothersSistersSon)
  case "CNLabelContactRelationElderCousinMothersSistersSon":
    return cnrCString(CNLabelContactRelationElderCousinMothersSistersSon)
  case "CNLabelContactRelationCousinMothersBrothersDaughter":
    return cnrCString(CNLabelContactRelationCousinMothersBrothersDaughter)
  case "CNLabelContactRelationYoungerCousinMothersBrothersDaughter":
    return cnrCString(CNLabelContactRelationYoungerCousinMothersBrothersDaughter)
  case "CNLabelContactRelationElderCousinMothersBrothersDaughter":
    return cnrCString(CNLabelContactRelationElderCousinMothersBrothersDaughter)
  case "CNLabelContactRelationCousinMothersBrothersSon":
    return cnrCString(CNLabelContactRelationCousinMothersBrothersSon)
  case "CNLabelContactRelationYoungerCousinMothersBrothersSon":
    return cnrCString(CNLabelContactRelationYoungerCousinMothersBrothersSon)
  case "CNLabelContactRelationElderCousinMothersBrothersSon":
    return cnrCString(CNLabelContactRelationElderCousinMothersBrothersSon)
  case "CNLabelContactRelationCousinFathersSistersDaughter":
    return cnrCString(CNLabelContactRelationCousinFathersSistersDaughter)
  case "CNLabelContactRelationYoungerCousinFathersSistersDaughter":
    return cnrCString(CNLabelContactRelationYoungerCousinFathersSistersDaughter)
  case "CNLabelContactRelationElderCousinFathersSistersDaughter":
    return cnrCString(CNLabelContactRelationElderCousinFathersSistersDaughter)
  case "CNLabelContactRelationCousinFathersSistersSon":
    return cnrCString(CNLabelContactRelationCousinFathersSistersSon)
  case "CNLabelContactRelationYoungerCousinFathersSistersSon":
    return cnrCString(CNLabelContactRelationYoungerCousinFathersSistersSon)
  case "CNLabelContactRelationElderCousinFathersSistersSon":
    return cnrCString(CNLabelContactRelationElderCousinFathersSistersSon)
  case "CNLabelContactRelationCousinFathersBrothersDaughter":
    return cnrCString(CNLabelContactRelationCousinFathersBrothersDaughter)
  case "CNLabelContactRelationYoungerCousinFathersBrothersDaughter":
    return cnrCString(CNLabelContactRelationYoungerCousinFathersBrothersDaughter)
  case "CNLabelContactRelationElderCousinFathersBrothersDaughter":
    return cnrCString(CNLabelContactRelationElderCousinFathersBrothersDaughter)
  case "CNLabelContactRelationCousinFathersBrothersSon":
    return cnrCString(CNLabelContactRelationCousinFathersBrothersSon)
  case "CNLabelContactRelationYoungerCousinFathersBrothersSon":
    return cnrCString(CNLabelContactRelationYoungerCousinFathersBrothersSon)
  case "CNLabelContactRelationElderCousinFathersBrothersSon":
    return cnrCString(CNLabelContactRelationElderCousinFathersBrothersSon)
  case "CNLabelContactRelationCousinGrandparentsSiblingsChild":
    return cnrCString(CNLabelContactRelationCousinGrandparentsSiblingsChild)
  case "CNLabelContactRelationCousinGrandparentsSiblingsDaughter":
    return cnrCString(CNLabelContactRelationCousinGrandparentsSiblingsDaughter)
  case "CNLabelContactRelationCousinGrandparentsSiblingsSon":
    return cnrCString(CNLabelContactRelationCousinGrandparentsSiblingsSon)
  case "CNLabelContactRelationYoungerCousinMothersSiblingsSonOrFathersSistersSon":
    return cnrCString(CNLabelContactRelationYoungerCousinMothersSiblingsSonOrFathersSistersSon)
  case "CNLabelContactRelationElderCousinMothersSiblingsSonOrFathersSistersSon":
    return cnrCString(CNLabelContactRelationElderCousinMothersSiblingsSonOrFathersSistersSon)
  case "CNLabelContactRelationYoungerCousinMothersSiblingsDaughterOrFathersSistersDaughter":
    return cnrCString(CNLabelContactRelationYoungerCousinMothersSiblingsDaughterOrFathersSistersDaughter)
  case "CNLabelContactRelationElderCousinMothersSiblingsDaughterOrFathersSistersDaughter":
    return cnrCString(CNLabelContactRelationElderCousinMothersSiblingsDaughterOrFathersSistersDaughter)
  case "CNLabelContactRelationParentsSibling":
    return cnrCString(CNLabelContactRelationParentsSibling)
  case "CNLabelContactRelationParentsYoungerSibling":
    return cnrCString(CNLabelContactRelationParentsYoungerSibling)
  case "CNLabelContactRelationParentsElderSibling":
    return cnrCString(CNLabelContactRelationParentsElderSibling)
  case "CNLabelContactRelationParentsSiblingMothersSibling":
    return cnrCString(CNLabelContactRelationParentsSiblingMothersSibling)
  case "CNLabelContactRelationParentsSiblingMothersYoungerSibling":
    return cnrCString(CNLabelContactRelationParentsSiblingMothersYoungerSibling)
  case "CNLabelContactRelationParentsSiblingMothersElderSibling":
    return cnrCString(CNLabelContactRelationParentsSiblingMothersElderSibling)
  case "CNLabelContactRelationParentsSiblingFathersSibling":
    return cnrCString(CNLabelContactRelationParentsSiblingFathersSibling)
  case "CNLabelContactRelationParentsSiblingFathersYoungerSibling":
    return cnrCString(CNLabelContactRelationParentsSiblingFathersYoungerSibling)
  case "CNLabelContactRelationParentsSiblingFathersElderSibling":
    return cnrCString(CNLabelContactRelationParentsSiblingFathersElderSibling)
  case "CNLabelContactRelationAunt":
    return cnrCString(CNLabelContactRelationAunt)
  case "CNLabelContactRelationAuntParentsSister":
    return cnrCString(CNLabelContactRelationAuntParentsSister)
  case "CNLabelContactRelationAuntParentsYoungerSister":
    return cnrCString(CNLabelContactRelationAuntParentsYoungerSister)
  case "CNLabelContactRelationAuntParentsElderSister":
    return cnrCString(CNLabelContactRelationAuntParentsElderSister)
  case "CNLabelContactRelationAuntFathersSister":
    return cnrCString(CNLabelContactRelationAuntFathersSister)
  case "CNLabelContactRelationAuntFathersYoungerSister":
    return cnrCString(CNLabelContactRelationAuntFathersYoungerSister)
  case "CNLabelContactRelationAuntFathersElderSister":
    return cnrCString(CNLabelContactRelationAuntFathersElderSister)
  case "CNLabelContactRelationAuntFathersBrothersWife":
    return cnrCString(CNLabelContactRelationAuntFathersBrothersWife)
  case "CNLabelContactRelationAuntFathersYoungerBrothersWife":
    return cnrCString(CNLabelContactRelationAuntFathersYoungerBrothersWife)
  case "CNLabelContactRelationAuntFathersElderBrothersWife":
    return cnrCString(CNLabelContactRelationAuntFathersElderBrothersWife)
  case "CNLabelContactRelationAuntMothersSister":
    return cnrCString(CNLabelContactRelationAuntMothersSister)
  case "CNLabelContactRelationAuntMothersYoungerSister":
    return cnrCString(CNLabelContactRelationAuntMothersYoungerSister)
  case "CNLabelContactRelationAuntMothersElderSister":
    return cnrCString(CNLabelContactRelationAuntMothersElderSister)
  case "CNLabelContactRelationAuntMothersBrothersWife":
    return cnrCString(CNLabelContactRelationAuntMothersBrothersWife)
  case "CNLabelContactRelationGrandaunt":
    return cnrCString(CNLabelContactRelationGrandaunt)
  case "CNLabelContactRelationUncle":
    return cnrCString(CNLabelContactRelationUncle)
  case "CNLabelContactRelationUncleParentsBrother":
    return cnrCString(CNLabelContactRelationUncleParentsBrother)
  case "CNLabelContactRelationUncleParentsYoungerBrother":
    return cnrCString(CNLabelContactRelationUncleParentsYoungerBrother)
  case "CNLabelContactRelationUncleParentsElderBrother":
    return cnrCString(CNLabelContactRelationUncleParentsElderBrother)
  case "CNLabelContactRelationUncleMothersBrother":
    return cnrCString(CNLabelContactRelationUncleMothersBrother)
  case "CNLabelContactRelationUncleMothersYoungerBrother":
    return cnrCString(CNLabelContactRelationUncleMothersYoungerBrother)
  case "CNLabelContactRelationUncleMothersElderBrother":
    return cnrCString(CNLabelContactRelationUncleMothersElderBrother)
  case "CNLabelContactRelationUncleMothersSistersHusband":
    return cnrCString(CNLabelContactRelationUncleMothersSistersHusband)
  case "CNLabelContactRelationUncleFathersBrother":
    return cnrCString(CNLabelContactRelationUncleFathersBrother)
  case "CNLabelContactRelationUncleFathersYoungerBrother":
    return cnrCString(CNLabelContactRelationUncleFathersYoungerBrother)
  case "CNLabelContactRelationUncleFathersElderBrother":
    return cnrCString(CNLabelContactRelationUncleFathersElderBrother)
  case "CNLabelContactRelationUncleFathersSistersHusband":
    return cnrCString(CNLabelContactRelationUncleFathersSistersHusband)
  case "CNLabelContactRelationUncleFathersYoungerSistersHusband":
    return cnrCString(CNLabelContactRelationUncleFathersYoungerSistersHusband)
  case "CNLabelContactRelationUncleFathersElderSistersHusband":
    return cnrCString(CNLabelContactRelationUncleFathersElderSistersHusband)
  case "CNLabelContactRelationGranduncle":
    return cnrCString(CNLabelContactRelationGranduncle)
  case "CNLabelContactRelationSiblingsChild":
    return cnrCString(CNLabelContactRelationSiblingsChild)
  case "CNLabelContactRelationNiece":
    return cnrCString(CNLabelContactRelationNiece)
  case "CNLabelContactRelationNieceSistersDaughter":
    return cnrCString(CNLabelContactRelationNieceSistersDaughter)
  case "CNLabelContactRelationNieceBrothersDaughter":
    return cnrCString(CNLabelContactRelationNieceBrothersDaughter)
  case "CNLabelContactRelationNieceSistersDaughterOrWifesSiblingsDaughter":
    return cnrCString(CNLabelContactRelationNieceSistersDaughterOrWifesSiblingsDaughter)
  case "CNLabelContactRelationNieceBrothersDaughterOrHusbandsSiblingsDaughter":
    return cnrCString(CNLabelContactRelationNieceBrothersDaughterOrHusbandsSiblingsDaughter)
  case "CNLabelContactRelationNephew":
    return cnrCString(CNLabelContactRelationNephew)
  case "CNLabelContactRelationNephewSistersSon":
    return cnrCString(CNLabelContactRelationNephewSistersSon)
  case "CNLabelContactRelationNephewBrothersSon":
    return cnrCString(CNLabelContactRelationNephewBrothersSon)
  case "CNLabelContactRelationNephewBrothersSonOrHusbandsSiblingsSon":
    return cnrCString(CNLabelContactRelationNephewBrothersSonOrHusbandsSiblingsSon)
  case "CNLabelContactRelationNephewSistersSonOrWifesSiblingsSon":
    return cnrCString(CNLabelContactRelationNephewSistersSonOrWifesSiblingsSon)
  case "CNLabelContactRelationGrandniece":
    return cnrCString(CNLabelContactRelationGrandniece)
  case "CNLabelContactRelationGrandnieceSistersGranddaughter":
    return cnrCString(CNLabelContactRelationGrandnieceSistersGranddaughter)
  case "CNLabelContactRelationGrandnieceBrothersGranddaughter":
    return cnrCString(CNLabelContactRelationGrandnieceBrothersGranddaughter)
  case "CNLabelContactRelationGrandnephew":
    return cnrCString(CNLabelContactRelationGrandnephew)
  case "CNLabelContactRelationGrandnephewSistersGrandson":
    return cnrCString(CNLabelContactRelationGrandnephewSistersGrandson)
  case "CNLabelContactRelationGrandnephewBrothersGrandson":
    return cnrCString(CNLabelContactRelationGrandnephewBrothersGrandson)
  case "CNLabelContactRelationStepparent":
    return cnrCString(CNLabelContactRelationStepparent)
  case "CNLabelContactRelationStepmother":
    return cnrCString(CNLabelContactRelationStepmother)
  case "CNLabelContactRelationStepfather":
    return cnrCString(CNLabelContactRelationStepfather)
  case "CNLabelContactRelationStepchild":
    return cnrCString(CNLabelContactRelationStepchild)
  case "CNLabelContactRelationStepdaughter":
    return cnrCString(CNLabelContactRelationStepdaughter)
  case "CNLabelContactRelationStepson":
    return cnrCString(CNLabelContactRelationStepson)
  case "CNLabelContactRelationStepsister":
    return cnrCString(CNLabelContactRelationStepsister)
  case "CNLabelContactRelationStepbrother":
    return cnrCString(CNLabelContactRelationStepbrother)
  case "CNLabelContactRelationMotherInLawOrStepmother":
    return cnrCString(CNLabelContactRelationMotherInLawOrStepmother)
  case "CNLabelContactRelationFatherInLawOrStepfather":
    return cnrCString(CNLabelContactRelationFatherInLawOrStepfather)
  case "CNLabelContactRelationDaughterInLawOrStepdaughter":
    return cnrCString(CNLabelContactRelationDaughterInLawOrStepdaughter)
  case "CNLabelContactRelationSonInLawOrStepson":
    return cnrCString(CNLabelContactRelationSonInLawOrStepson)
  case "CNLabelContactRelationCousinOrSiblingsChild":
    return cnrCString(CNLabelContactRelationCousinOrSiblingsChild)
  case "CNLabelContactRelationNieceOrCousin":
    return cnrCString(CNLabelContactRelationNieceOrCousin)
  case "CNLabelContactRelationNephewOrCousin":
    return cnrCString(CNLabelContactRelationNephewOrCousin)
  case "CNLabelContactRelationGrandchildOrSiblingsChild":
    return cnrCString(CNLabelContactRelationGrandchildOrSiblingsChild)
  case "CNLabelContactRelationGranddaughterOrNiece":
    return cnrCString(CNLabelContactRelationGranddaughterOrNiece)
  case "CNLabelContactRelationGrandsonOrNephew":
    return cnrCString(CNLabelContactRelationGrandsonOrNephew)
  case "CNLabelContactRelationGreatGrandchildOrSiblingsGrandchild":
    return cnrCString(CNLabelContactRelationGreatGrandchildOrSiblingsGrandchild)
  case "CNLabelContactRelationDaughterInLawOrSisterInLaw":
    return cnrCString(CNLabelContactRelationDaughterInLawOrSisterInLaw)
  case "CNLabelContactRelationSonInLawOrBrotherInLaw":
    return cnrCString(CNLabelContactRelationSonInLawOrBrotherInLaw)
  default:
    cnrSetMessageError(outError, message: "unknown Contacts constant symbol: \(symbol)")
    return nil
  }
}
